version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: maksim1992/foodgram_final:latest
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend

  frontend:
    image: maksim1992/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

volumes:
  static_value:
  media_value:
  db-data:

